ALTER TABLE provinces_m ADD COLUMN code VARCHAR(40);
ALTER TABLE cities_m ADD COLUMN code VARCHAR(40);
ALTER TABLE subdistrict_m ADD COLUMN code VARCHAR(40);
ALTER TABLE villages_m ADD COLUMN code VARCHAR(40);
