package seeders

import (
	dept "backend-app/internal/modules/master/model/department"

	"gorm.io/gorm"
)

func SeedDepartmentWards(db *gorm.DB, profileID uint32) error {
	// Create department: Rawat Jalan
	department := dept.Department{
		BaseModel:      createBaseModel(profileID, nil),
		DepartmentName: "Rawat Jalan",
	}
	if err := db.Create(&department).Error; err != nil {
		return err
	}

	wards := []string{
		"Akupuntur Medik",
		"Anak Hematologi Onkologi",
		"Anak Infeksi & Pediatri Tropis",
		"Anak Kardiologi",
		"Anak Nefrologi",
		"Anak Neurologi",
		"Anak Nutrisi & Penyakit Metabolik",
		"Pediatri Gawat Darurat",
		"Pencitraan Anak",
		"Perinatologi",
		"Respirologi Anak",
		"Tumbuh Kembang Ped. Sosial",
		"Kesehatan Remaja",
		"Emergensi Dan Rawat Intensif Anak (Eria)",
		"Neonatologi",
		"Bedah Saraf",
		"Andrologi",
		"Intensive Care/Icu",
		"Anestesi Kardiovaskuler",
		"Terapi Nyeri",
		"Regional Anestesi",
		"Neuroanestesi",
		"Anestesi Pediatri",
		"Anestesi Obstetri",
		"Anastesi",
		"Bedah Digestif Anak",
		"Urogenital Anak",
		"Bedah Anak",
		"Gigi Bedah Mulut",
		"Burn (Luka Bakar)",
		"Micro Surgery",
		"Kraniofasial (Kkf)",
		"Hand (Bedah Tangan)",
		"Genitalia Eksterna",
		"Bedah Plastik",
		"Bedah Onkologi",
		"Bedah Digestif",
		"Bedah Vaskuler",
		"Bedah",
		"Bedah Kepala Leher",
		"Neurotrauma",
		"Neuropediatri",
		"Neuroonkologi",
		"Neurospine",
		"Neurofungsi-Onal",
		"Neurovaskular",
		"Gigi",
		"Emergensi",
		"Farmakologi Klinik",
		"Forensik",
		"Anak",
		"Gizi Klinik",
		"Gigi Endodonsi",
		"Gigi Orthodonti",
		"Gigi Periodonti",
		"Gigi Radiologi",
		"Alergi-Immunologi Klinik",
		"Geriatri",
		"Ginjal-Hipertensi",
		"BTKV",
		"Hematologi - Onkologi Medik",
		"Anak Endokrinologi",
		"Endokrin-Metabolik-Diabetes",
		"Psikosomatik",
		"Pulmonologi",
		"Reumatologi",
		"Penyakit Tropik-Infeksi",
		"Kardiovaskular",
		"Pediatri",
		"Geriatri",
		"Muskuloskeletal",
		"Neomuskuler",
		"Kardiorespirasi",
		"Pelayanan Aritmia",
		"Pelayanan Jantung Anak Dan Pjb",
		"Pelayanan Vaskular",
		"Pelayanan Cardiac Imaging",
		"Pelayanan Intensive Dan Kegawatan Kardiovas-Kuler",
		"Jantung Dan Pembuluh Darah",
		"Neuropsikiatri Dan Psikometri",
		"Psikoterapi",
		"Kesehatan Jiwa Anak Dan Remaja",
		"Psikiatri Geriatri",
		"Psikiatri Adiksi",
		"Consultation-Liaison Psychiatri",
		"Psikiatri Forensik",
		"Psikiatri Komunitas",
		"Jiwa",
		"Kedokteran Kelautan",
		"Kedokteran Nuklir Dan Pencitraan Molekular",
		"Kedokteran Okupasi",
		"Kedokteran Penerbangan",
		"Dermatologi Infeksi Tropik",
		"Dermatologi Pediatrik",
		"Dermatologi Kosmetik",
		"Infeksi Menular Seksual",
		"Dermatologi Geriatrik",
		"Tumor Dan Bedah Kulit",
		"Dermatopatologi",
		"Kulit Kelamin",
		"Gigi Pedodontis",
		"Kedokteraan Olahraga",
		"Kornea, Lensa Dan Bedah Refraktif",
		"Infeksi Dan Immunologi",
		"Vitreo - Retina",
		"Pediatri Onkologi Strabismus",
		"Neuro Oftalmologi",
		"Glaukoma",
		"Pediatrik Oftalmologi",
		"Refraksi Lensa Kontak",
		"Rekonstruksi Okuloplasti Dan Onkologi",
		"Onkologi Mata",
		"Oftalmologi Komunitas",
		"Mata",
		"Mikrobiologi Klinik",
		"Fetomaternal",
		"Onkologi Ginekologi",
		"Uroginekologi Dan Rekonstruksi",
		"Obstetri Ginekologi Sosial",
		"Endokrinologi",
		"Fertilitas Dan Endokrinologi Reproduksi",
		"Obgyn",
		"Trauma Dan Rekonstruksi",
		"Spine",
		"Tumor Muskuloskeletal",
		"Paediatric Orthopaedi",
		"Sport, Shoulder And Elbow",
		"Hip And Knee",
		"Bio Orthopedic",
		"Penyakit Dalam",
		"THT-KL",
		"Orthopedi",
		"Patologi Anatomi",
		"Infeksi",
		"Hematologi",
		"Imunologi",
		"Kardiocerbrovaskuler",
		"Nefrologi",
		"Hepatogastroenterologi",
		"Endokrin Dan Metabolisme",
		"Onkologi",
		"Bank Darah Dan Kedokteran Laboratorium",
		"Patologi Klinik",
		"Infeksi Paru",
		"Onkologi Toraks",
		"Asma Ppok",
		"Intervensi Dan Gawat Nafas",
		"Faal Paru Klinik",
		"Paru Kerja Dan Lingkungan",
		"Imunologi Paru",
		"Paru",
		"Gigi Penyakit Mulut",
		"Parasitologi Umum",
		"Gigi Prsosthodonti",
		"Radiologi Onkologi",
		"Thorax Imaging",
		"Radiologi Tr Urinariusgenitalia",
		"Radiologi Tr Digestivus",
		"Radiologi Neuro Kepala Leher",
		"Breast And Women Imaging",
		"Radiologi Intervensional Kardiovaskular",
		"Pencitraan Kepala Leher",
		"Radiologi Pediatrik",
		"Radiologi Nuklir",
		"Imaging Abdomen",
		"Radioterapi",
		"Neurointerven-Si",
		"Neuroinfeksi",
		"Neuroinfeksi Dan Imunologi",
		"Epilepsi",
		"Neurofisiologi Klinis",
		"Neuromuskular, Saraf Perifer",
		"Neurobehaviour, Md, Neurogeriatri, Dan Neurorestorasi",
		"Neuro-Oftalmologi Dan Neuro-Otologi",
		"Neuro-Intensif",
		"Manajemen Intervensi Nyeri",
		"Fungsi Luhur",
		"Eurosonologi",
		"Saraf",
		"Urologi",
		"THT Komunitas",
		"Otologi",
		"Neurotologi",
		"Rinologi",
		"Onkologi Bedah Kepala Leher",
		"Plastik Rekontruksi THT",
		"Endoskopi Bronko-Esofagologi",
		"Alergi Imunologi",
		"Umum",
		"Poliklinik Kulit dan Kelamin",
		"Anak Alergi Imunologi",
		"Anak Gastro-Hepatologi",
		"Laring Faring",
		"Rekontruksi Dan Estetik",
		"Gastroenterologi-Hepatologi",
		"Hepatologi",
		"Rehabilitasi Medik",
		"Dermato - Alergo - Imunologi",
		"Hand And Microsurgery",
		"Foot And Ankle",
		"Radiologi Muskuloskeletal",
		"Visum Sentral",
		"Medical Check Up",
		"Hemodialisis",
	}

	for _, name := range wards {
		ward := dept.Ward{
			BaseModel:    createBaseModel(profileID, nil),
			WardName:     name,
			DepartmentID: &department.ID,
		}
		if err := db.Create(&ward).Error; err != nil {
			return err
		}
	}

	return nil
}
