app:
  name: "SIMRS Enterprise"
  port: 8081
  env: "development"
  appname: "HIS"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "root"
  name: "his_database"
  sslmode: "disable"

log:
  level: "debug"
