// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package master

import (
	"backend-app/config"
	"backend-app/internal/modules/master/controller"
	"backend-app/internal/modules/master/repository/permission"
	"backend-app/internal/modules/master/repository/registry"
	"backend-app/internal/modules/master/repository/role"
	"backend-app/internal/modules/master/repository/user"
	permission2 "backend-app/internal/modules/master/service/permission"
	registry2 "backend-app/internal/modules/master/service/registry"
	role2 "backend-app/internal/modules/master/service/role"
	user2 "backend-app/internal/modules/master/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeMasterRouter(cfg *config.Config, db *gorm.DB) *MasterRouter {
	userRepository := user.NewUserRepository(db)
	userService := user2.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	roleRepository := role.NewRoleRepository(db)
	roleService := role2.NewRoleService(roleRepository)
	roleController := controller.NewRoleController(roleService)
	registryRepository := registry.NewRegistryRepository(db)
	registryService := registry2.NewRegistryService(registryRepository)
	registryController := controller.NewRegistryController(registryService)
	permissionRepository := permission.NewPermissionRepository(db)
	permissionService := permission2.NewPermissionService(permissionRepository)
	permissionController := controller.NewPermissionController(permissionService)
	masterRouter := NewMasterRouter(userController, roleController, registryController, permissionController)
	return masterRouter
}
