// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package master

import (
	"backend-app/config"
	"backend-app/internal/modules/master/controller"
	"backend-app/internal/modules/master/controller/employee"
	"backend-app/internal/modules/master/controller/general"
	"backend-app/internal/modules/master/repository/employee/employment_status"
	"backend-app/internal/modules/master/repository/employee/job_category"
	"backend-app/internal/modules/master/repository/employee/job_title"
	"backend-app/internal/modules/master/repository/general/gender"
	"backend-app/internal/modules/master/repository/general/religion"
	"backend-app/internal/modules/master/repository/permission"
	"backend-app/internal/modules/master/repository/registry"
	"backend-app/internal/modules/master/repository/role"
	"backend-app/internal/modules/master/repository/user"
	employment_status2 "backend-app/internal/modules/master/service/employee/employment_status"
	job_category2 "backend-app/internal/modules/master/service/employee/job_category"
	job_title2 "backend-app/internal/modules/master/service/employee/job_title"
	gender2 "backend-app/internal/modules/master/service/general/gender"
	religion2 "backend-app/internal/modules/master/service/general/religion"
	permission2 "backend-app/internal/modules/master/service/permission"
	registry2 "backend-app/internal/modules/master/service/registry"
	role2 "backend-app/internal/modules/master/service/role"
	user2 "backend-app/internal/modules/master/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeMasterRouter(cfg *config.Config, db *gorm.DB) *MasterRouter {
	userRepository := user.NewUserRepository(db)
	userService := user2.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	roleRepository := role.NewRoleRepository(db)
	roleService := role2.NewRoleService(roleRepository)
	roleController := controller.NewRoleController(roleService)
	registryRepository := registry.NewRegistryRepository(db)
	registryService := registry2.NewRegistryService(registryRepository)
	registryController := controller.NewRegistryController(registryService)
	permissionRepository := permission.NewPermissionRepository(db)
	permissionService := permission2.NewPermissionService(permissionRepository)
	permissionController := controller.NewPermissionController(permissionService)
	religionRepository := religion.NewReligionRepository(db)
	religionService := religion2.NewReligionService(religionRepository)
	religionController := general.NewReligionController(religionService)
	genderRepository := gender.NewGenderRepository(db)
	genderService := gender2.NewGenderService(genderRepository)
	genderController := general.NewGenderController(genderService)
	jobCategoryRepository := job_category.NewJobCategoryRepository(db)
	jobCategoryService := job_category2.NewJobCategoryService(jobCategoryRepository)
	jobCategoryController := employee.NewJobCategoryController(jobCategoryService)
	jobTitleRepository := job_title.NewJobTitleRepository(db)
	jobTitleService := job_title2.NewJobTitleService(jobTitleRepository, jobCategoryRepository)
	jobTitleController := employee.NewJobTitleController(jobTitleService)
	employmentStatusRepository := employment_status.NewEmploymentStatusRepository(db)
	employmentStatusService := employment_status2.NewEmploymentStatusService(employmentStatusRepository)
	employmentStatusController := employee.NewEmploymentStatusController(employmentStatusService)
	masterRouter := NewMasterRouter(userController, roleController, registryController, permissionController, religionController, genderController, jobCategoryController, jobTitleController, employmentStatusController)
	return masterRouter
}
