// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package master

import (
	"backend-app/config"
	"backend-app/internal/modules/auth/repository/personal_access_token"
	"backend-app/internal/modules/master/controller"
	"backend-app/internal/modules/master/repository/role"
	"backend-app/internal/modules/master/repository/user"
	role2 "backend-app/internal/modules/master/service/role"
	user2 "backend-app/internal/modules/master/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeMasterRouter(cfg *config.Config, db *gorm.DB) *MasterRouter {
	userRepository := user.NewUserRepository(db)
	userService := user2.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	roleRepository := role.NewRoleRepository(db)
	roleService := role2.NewRoleService(roleRepository)
	roleController := controller.NewRoleController(roleService)
	tokenRepository := personal_access_token.NewTokenRepository(db)
	masterRouter := NewMasterRouter(userController, roleController, cfg, tokenRepository)
	return masterRouter
}
