// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"backend-app/config"
	"backend-app/internal/modules/auth/controller"
	"backend-app/internal/modules/auth/repository/personal_access_token"
	"backend-app/internal/modules/auth/repository/user"
	user2 "backend-app/internal/modules/auth/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthRouter(cfg *config.Config, db *gorm.DB) *AuthRouter {
	userRepository := user.NewUserRepository(db)
	tokenRepository := personal_access_token.NewTokenRepository(db)
	userService := user2.NewUserService(userRepository, tokenRepository, cfg)
	authController := controller.NewAuthController(userService)
	authRouter := NewAuthRouter(authController)
	return authRouter
}
