// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"backend-app/config"
	"backend-app/internal/modules/auth/controller"
	"backend-app/internal/modules/auth/repository/menu"
	"backend-app/internal/modules/auth/repository/module"
	"backend-app/internal/modules/auth/repository/permission"
	"backend-app/internal/modules/auth/repository/personal_access_token"
	"backend-app/internal/modules/auth/repository/user"
	"backend-app/internal/modules/auth/service/auth"
	menu2 "backend-app/internal/modules/auth/service/menu"
	permission2 "backend-app/internal/modules/auth/service/permission"
	user2 "backend-app/internal/modules/auth/service/user"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAuthRouter(cfg *config.Config, db *gorm.DB) *AuthRouter {
	userRepository := user.NewUserRepository(db)
	tokenRepository := personal_access_token.NewTokenRepository(db)
	authService := auth.NewAuthService(userRepository, tokenRepository, cfg)
	authController := controller.NewAuthController(authService)
	userService := user2.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	menuInterface := menu.NewMenuRepository(db)
	moduleRepository := module.NewModuleRepository(db)
	menuService := menu2.NewMenuService(menuInterface, moduleRepository)
	menuController := controller.NewMenuController(menuService, userRepository)
	permissionRepository := permission.NewPermissionRepository(db)
	permissionService := permission2.NewPermissionService(permissionRepository, userRepository)
	permissionController := controller.NewPermissionController(permissionService)
	authRouter := NewAuthRouter(authController, userController, menuController, permissionController, cfg, tokenRepository)
	return authRouter
}
